spring:
  data:
    redis:
      host: redis
      port: 6379
      database: 0
      timeout: 3s
  kafka:
    bootstrap-servers: kafka:9092
  cloud:
    sentinel:
      transport:
        dashboard: sentinel-dashboard:8858
      eager: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,sentinel
