server:
  port: 8083

spring:
  application:
    name: seckill-payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

mybatis:
  configuration:
    map-underscore-to-camel-case: true

app:
  kafka:
    payment-result-topic: payment-result-topic
