server:
  port: 8081

spring:
  datasource:
    url: ${INVENTORY_DB_URL:jdbc:mysql://localhost:3306/inventory_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai}
    username: ${INVENTORY_DB_USERNAME:root}
    password: ${INVENTORY_DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: 0
      timeout: 3s
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: inventory-service-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  cloud:
    sentinel:
      transport:
        dashboard: ${SENTINEL_DASHBOARD_ADDR:localhost:8858}
      eager: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,sentinel

app:
  runtime:
    message: inventory local runtime message
  limit:
    internal-qps: ${INVENTORY_INTERNAL_QPS:80}
  kafka:
    inventory-deduct-topic: inventory-deduct-topic
    inventory-result-topic: inventory-deduct-result-topic
